name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image - frontend
      run: docker build "Sprint 3/frontend" --tag docker.registry.ampstudios.games/misc/soen341:latest
    - name: Deploy - frontend
      run: docker push docker.registry.ampstudios.games/misc/soen341:latest
    - name: Build the Docker image - backend
      run: docker build "Sprint 3/backend" --tag docker.registry.ampstudios.games/misc/soen341-backend:latest
    - name: Deploy - backend
      run: docker push docker.registry.ampstudios.games/misc/soen341-backend:latest
    - name: Webhook POST Action
      uses: muinmomin/webhook-action@v1.0.0
      with:
        # URL of webhook to send post request to
        url: https://firport.dynv6.net/api/stacks/webhooks/af2adf10-dae8-4cbf-8410-b7ebbdf49445
